import type { TherapyToy } from './therapy-toys-types';

export const therapyToys: TherapyToy[] = [
  {
    id: 'rainbow-stacking-rings',
    title: 'Rainbow Stacking Rings',
    brand: "Grimm's",
    category: 'Fine Motor',
    ageRange: '6 months – 3 years',
    primarySkill: 'Fine Motor',
    membership: 'Little Steps',
    status: 'Published',
    updatedAt: 'Mar 28, 2025',
  },
  {
    id: 'wooden-balance-board',
    title: 'Wooden Balance Board',
    brand: 'Wobbel',
    category: 'Gross Motor',
    ageRange: '18 months – 6 years',
    primarySkill: 'Balance',
    membership: 'Grow Together',
    status: 'Published',
    updatedAt: 'Mar 24, 2025',
  },
  {
    id: 'therapy-putty-kit',
    title: 'Therapy Putty Kit',
    brand: 'CanDo',
    category: 'Sensory',
    ageRange: '3 – 8 years',
    primarySkill: 'Hand Strength',
    membership: 'Little Steps',
    status: 'Published',
    updatedAt: 'Mar 18, 2025',
  },
  {
    id: 'textured-sensory-stones',
    title: 'Textured Sensory Stones',
    brand: 'Yellow Door',
    category: 'Sensory',
    ageRange: '12 months – 5 years',
    primarySkill: 'Tactile Play',
    membership: 'Grow Together',
    status: 'Draft',
    updatedAt: 'Mar 14, 2025',
  },
  {
    id: 'lacing-beads-set',
    title: 'Lacing Beads Set',
    brand: 'Melissa & Doug',
    category: 'Fine Motor',
    ageRange: '2 – 5 years',
    primarySkill: 'Bilateral Coordination',
    membership: 'Little Steps',
    status: 'Published',
    updatedAt: 'Mar 8, 2025',
  },
  {
    id: 'visual-tracking-wand',
    title: 'Visual Tracking Wand',
    brand: 'Playlearn',
    category: 'Visual Motor',
    ageRange: '18 months – 4 years',
    primarySkill: 'Visual Tracking',
    membership: 'Personalized Pathways',
    status: 'Published',
    updatedAt: 'Mar 2, 2025',
  },
  {
    id: 'weighted-lap-pad',
    title: 'Weighted Lap Pad',
    brand: 'SensaCalm',
    category: 'Regulation',
    ageRange: '3 – 8 years',
    primarySkill: 'Self Regulation',
    membership: 'Grow Together',
    status: 'Draft',
    updatedAt: 'Feb 26, 2025',
  },
];

export const therapyToyMetrics = [
  { value: '94', label: 'Total Toys', tone: 'green' },
  { value: '18', label: 'Published', tone: 'yellow' },
  { value: '84%', label: 'Drafts', tone: 'orange' },
  { value: '312', label: 'Categories', tone: 'cyan' },
] as const;
