import type { ParentResource } from './parent-resources-types';

export const parentResources: ParentResource[] = [
  {
    id: 'sensory-processing',
    title: 'Understanding Sensory Processing in Young Children',
    author: 'Sarah K.',
    readTime: '8 min read',
    category: 'Sensory Development',
    type: 'Article',
    membership: 'Little Steps',
    downloads: 0,
    status: 'Published',
    updatedAt: 'Apr 2, 2025',
  },
  {
    id: 'fine-motor',
    title: 'Fine Motor Milestones: Birth to 5 Years',
    author: 'James R.',
    readTime: '12 min read',
    category: 'Fine Motor',
    type: 'Guide',
    membership: 'Little Steps',
    downloads: 89,
    status: 'Published',
    updatedAt: 'Mar 18, 2025',
  },
  {
    id: 'sleep-routines',
    title: 'Sleep Routines Guide for Toddlers',
    author: 'Sarah K.',
    readTime: '6 min read',
    category: 'Daily Living',
    type: 'PDF',
    membership: 'Grow Together',
    downloads: 134,
    status: 'Published',
    updatedAt: 'Mar 25, 2025',
  },
  {
    id: 'language-play',
    title: 'Building Language Skills Through Play',
    author: 'James R.',
    readTime: '10 min read',
    category: 'Communication',
    type: 'Article',
    membership: 'Little Steps',
    downloads: 0,
    status: 'Published',
    updatedAt: 'Mar 12, 2025',
  },
  {
    id: 'emotional-regulation',
    title: 'Emotional Regulation Toolkit for Parents',
    author: 'Sarah K.',
    readTime: '15 min read',
    category: 'Emotional Regulation',
    type: 'Printable',
    membership: 'Grow Together',
    downloads: 201,
    status: 'Published',
    updatedAt: 'Apr 1, 2025',
  },
  {
    id: 'gross-motor',
    title: 'Gross Motor Development: Ages 1–3',
    author: 'James R.',
    readTime: '7 min read',
    category: 'Gross Motor',
    type: 'Article',
    membership: 'Little Steps',
    downloads: 67,
    status: 'Published',
    updatedAt: 'Feb 28, 2025',
  },
  {
    id: 'picky-eating',
    title: 'Personalized Therapy: What to Expect',
    author: 'Sarah K.',
    readTime: '9 min read',
    category: 'Parent Education',
    type: 'Guide',
    membership: 'Personalized Pathways',
    downloads: 44,
    status: 'Published',
    updatedAt: 'Mar 30, 2025',
  },
  {
    id: 'summer-activities',
    title: 'Sensory-Friendly Home Environments',
    author: 'James R.',
    readTime: '5 min read',
    category: 'Sensory Development',
    type: 'Article',
    membership: 'Grow Together',
    downloads: 0,
    status: 'Draft',
    updatedAt: 'Apr 5, 2025',
  },
];

export const resourceMetrics = [
  { value: '94', label: 'Total Resources' },
  { value: '18', label: 'Published' },
  { value: '345', label: 'Resources Download' },
  { value: '2', label: 'Drafts' },
  { value: '2', label: 'Archived' },
];
