import type { ParentResource } from './parent-resources-types';

export const parentResources: ParentResource[] = [
  {
    id: 'sensory-processing',
    title: 'Understanding Sensory Processing in Young Children',
    summary:
      'A comprehensive guide to understanding how children process sensory information and how to support them at home.',
    author: 'Sarah K.',
    estimatedReadTime: '8 min read',
    category: 'Sensory Development',
    resourceType: 'ARTICLE',
    accessLevel: ['LITTLE_STEPS', 'GROW_TOGETHER', 'PERSONALIZED_PATHWAYS'],
    status: 'PUBLISHED',
    createdAt: '2025-04-02T10:00:00.000Z',
    updatedAt: '2025-04-02T10:00:00.000Z',
  },
  {
    id: 'fine-motor',
    title: 'Fine Motor Milestones: Birth to 5 Years',
    summary:
      'A detailed breakdown of key fine motor milestones from infant grasping to pencil grip.',
    author: 'James R.',
    estimatedReadTime: '12 min read',
    category: 'Fine Motor',
    resourceType: 'GUIDE',
    accessLevel: ['LITTLE_STEPS', 'GROW_TOGETHER', 'PERSONALIZED_PATHWAYS'],
    status: 'PUBLISHED',
    createdAt: '2025-03-18T10:00:00.000Z',
    updatedAt: '2025-03-18T10:00:00.000Z',
  },
  {
    id: 'sleep-routines',
    title: 'Sleep Routines Guide for Toddlers',
    summary: 'Practical sensory strategies for calm and consistent bedtime routines.',
    author: 'Sarah K.',
    estimatedReadTime: '6 min read',
    category: 'Daily Living',
    resourceType: 'PDF',
    accessLevel: ['GROW_TOGETHER', 'PERSONALIZED_PATHWAYS'],
    status: 'PUBLISHED',
    createdAt: '2025-03-25T10:00:00.000Z',
    updatedAt: '2025-03-25T10:00:00.000Z',
  },
  {
    id: 'language-play',
    title: 'Building Language Skills Through Play',
    summary: 'Simple language prompts and play routines for language-delayed toddlers.',
    author: 'James R.',
    estimatedReadTime: '10 min read',
    category: 'Communication',
    resourceType: 'ARTICLE',
    accessLevel: ['LITTLE_STEPS', 'GROW_TOGETHER', 'PERSONALIZED_PATHWAYS'],
    status: 'PUBLISHED',
    createdAt: '2025-03-12T10:00:00.000Z',
    updatedAt: '2025-03-12T10:00:00.000Z',
  },
  {
    id: 'emotional-regulation',
    title: 'Emotional Regulation Toolkit for Parents',
    summary: 'A toolkit of calming techniques and visual cue printables for dysregulated moments.',
    author: 'Sarah K.',
    estimatedReadTime: '15 min read',
    category: 'Emotional Regulation',
    resourceType: 'PRINTABLE',
    accessLevel: ['GROW_TOGETHER', 'PERSONALIZED_PATHWAYS'],
    status: 'PUBLISHED',
    createdAt: '2025-03-08T10:00:00.000Z',
    updatedAt: '2025-03-08T10:00:00.000Z',
  },
  {
    id: 'sensory-home',
    title: 'Sensory-Friendly Home Environments',
    summary: 'Designing calming spaces and low-sensory corners for overwhelmed toddlers.',
    author: 'James R.',
    estimatedReadTime: '5 min read',
    category: 'Sensory Development',
    resourceType: 'ARTICLE',
    accessLevel: ['GROW_TOGETHER', 'PERSONALIZED_PATHWAYS'],
    status: 'DRAFT',
    createdAt: '2025-04-05T10:00:00.000Z',
    updatedAt: '2025-04-05T10:00:00.000Z',
  },
];
